#ifndef _ENUMS_H_
#define _ENUMS_H_

enum CommandCode
{
    CMDCODE_FORCE_TRIGGER = 0x01,
    CMDCODE_TRIGGER_MODE = 0x02,
    CMDCODE_SET_RELAY = 0x03,
    CMDCODE_CHANNEL_SELECTION = 0x04,
    CMDCODE_TRIGGER_SOURCE = 0x05,
    CMDCODE_CHANNEL_VOLTS_DIV_125 = 0x06,
    CMDCODE_PRE_TRIGGER_LENGTH = 0x07,
    CMDCODE_POST_TRIGGER_LENGTH = 0x08,
    CMDCODE_RAM_START_POSITION = 0x09,
    CMDCODE_RESERVED_DATA_OUTPUT = 0x0a,
    CMDCODE_CH1_PWM = 0x0b,
    CMDCODE_CH2_PWM = 0x0c,
    CMDCODE_TRIGGER_PWM = 0x0d,
    CMDCODE_LOGIC_ANALYZER_1 = 0x0e,
    CMDCODE_LOGIC_ANALYZER_2 = 0x0f,
    CMDCODE_LOGIC_ANALYZER_4 = 0x10,
    CMDCODE_SAMPLE_RATE = 0x11,
    CMDCODE_FREQ_DIV_LOW = 0x12,
    CMDCODE_FREQ_DIV_HIGH = 0x13,
    CMDCODE_SERIAL_BAUD_RATE = 0x14,
    CMDCODE_RAM_CHANNEL_SELECTION = 0x15,
    CMDCODE_READ_RAM_COUNT = 0x16
};

enum Commands
{
    CMD_READ_FPGAVERSION_AND_EEPROM,
    CMD_UPDATE_TRIGGER_SOURCE,
    CMD_UPDATE_TIME_BASE,
    CMD_INITIALIZE,
    CMD_VOLTAGE_DIV,
    CMD_PULL_SAMPLES,
    CMD_CHANNEL_STATUS,
    CMD_CHANNEL_STATUS_ONLY,
    CMD_LEVELS,
    CMD_TRIGGER,
    CMD_X_TRIGGER_POS,
    CMD_CHANNEL1_VOLTAGE_DIV,
    CMD_CHANNEL2_VOLTAGE_DIV,

    CMD_READ_EEROM_PAGE00,
    CMD_READ_EEROM_PAGE04,
    CMD_READ_EEROM_PAGE05,
    CMD_READ_EEROM_PAGE07,
    CMD_READ_EEROM_PAGE08,
    CMD_READ_EEROM_PAGE09,
    CMD_READ_EEROM_PAGE0A,
    CMD_READ_EEROM_PAGE0B,
    CMD_READ_EEROM_PAGE0C,
    CMD_START_SAMPLING,
    CMD_SELECT_CHANNEL,
    CMD_SELECT_RAM_CHANNEL,
    CMD_READ_FPGA_VERSION,
    CMD_READ_BATTERY_LEVEL,
    CMD_READ_RAM_COUNT,
    CMD_GET_FREQDIV_LOW_BYTES,
    CMD_GET_FREQDIV_HIGH_BYTES,
    CMD_UPDATE_SAMPLE_RATE,
    CMD_UPDATE_TRIGGER_SOURCE_AND_SLOPE,
    CMD_UPDATE_TRIGGER_LEVEL,
    CMD_UPDATE_CHANNEL_VOLTS125,
    CMD_UPDATE_TRIGGER_MODE,
    CMD_RELAY1,
    CMD_RELAY2,
    CMD_RELAY3,
    CMD_RELAY4,
    CMD_CHANNEL1_LEVEL,
    CMD_CHANNEL2_LEVEL,
    CMD_CHANNEL1_COUPLING,
    CMD_CHANNEL2_COUPLING,
    CMD_PRE_TRIGGER,
    CMD_POST_TRIGGER
};

enum ParseChVoltsDivStatus
{
    PARSE_CHVOLTSDIV_S0,
    PARSE_CHVOLTSDIV_S125,
    PARSE_CHVOLTSDIV_SR1,
    PARSE_CHVOLTSDIV_SR2,
    PARSE_CHVOLTSDIV_S125R1,
    PARSE_CHVOLTSDIV_S125R2,
    PARSE_CHVOLTSDIV_SR1125,
    PARSE_CHVOLTSDIV_SR1R2,
    PARSE_CHVOLTSDIV_SR2R1,
    PARSE_CHVOLTSDIV_SR2125
};

enum TimeBase
{
    HDIV_5nS = 0,
    HDIV_10nS = 1,
    HDIV_20nS = 2,
    HDIV_50nS = 3,
    HDIV_100nS = 4,
    HDIV_200nS = 5,
    HDIV_500nS = 6,
    HDIV_1uS = 7,
    HDIV_2uS = 8,
    HDIV_5uS = 9,
    HDIV_10uS = 10,
    HDIV_20uS = 11,
    HDIV_50uS = 12,
    HDIV_100uS = 13,
    HDIV_200uS = 14,
    HDIV_500uS = 15,
    HDIV_1mS = 16,
    HDIV_2mS = 17,
    HDIV_5mS = 18,
    HDIV_10mS = 19,
    HDIV_20mS = 20,
    HDIV_50mS = 21,
    HDIV_100mS = 22,
    HDIV_200mS = 23,
    HDIV_500mS = 24,
    HDIV_1S = 25,
    HDIV_2S = 26,
    HDIV_5S = 27,
    HDIV_10S = 28,
    HDIV_20S = 29,
    HDIV_50S = 30,
    HDIV_100S = 31,
    HDIV_200S = 32,
    HDIV_500S = 33
};

enum VoltageDiv
{
    VDIV_10mV,
    VDIV_20mV,
    VDIV_50mV,
    VDIV_100mV,
    VDIV_200mV,
    VDIV_500mV,
    VDIV_1V,
    VDIV_2V,
    VDIV_5V
};

enum InputCoupling
{
    COUPLING_AC,
    COUPLING_DC,
    COUPLING_GND
};

enum CaptureMode
{
    CAPMODE_ROLL,
    CAPMODE_SCAN,
    CAPMODE_NORMAL
};

enum ScopeMode
{
    SCOMODE_ANALOG,
    SCOMODE_DIGITAL
};

enum TriggerChannel
{
    TRIGCHAN_CH1,
    TRIGCHAN_CH2,
    TRIGCHAN_EXT,
    TRIGCHAN_EXT10,
    TRIGCHAN_ALT
};

enum TriggerMode
{
    TRIGMODE_AUTO,
    TRIGMODE_NORMAL,
    TRIGMODE_SINGLE
};

enum TriggerSlope
{
    TRIGSLOPE_RISING,
    TRIGSLOPE_FALLING
};

#endif // _ENUMS_H_